In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
excel=pd.read_csv("ACSDP5Y2023.DP03-Data.csv")

Key things:

columns 105-122: number of houses at said price

column 240: (maybe 514 as well) percentage of families below the poverty line

COlumn 312-327: Commuting modeshare for workers


elderly data: 544 for elderly poverty, 134 mean social security payouts *for people who qualify*, 138 retirement income, 144-145 mean supplimental security

In [80]:
excel2=pd.read_csv('ACSST5Y2023.S2701-Data.csv') #redundant
#excel2.iloc[:,26] #number of OLD people
#excel2.iloc[:,148] #number of old people with insurance
#excel2.iloc[:,270] #percent insured
#excel2.iloc[:,392] #total uninsured
#excel2.iloc[:,514] #percent uninsured
#end of excel2

In [6]:
excel3=pd.read_csv('ACSST5Y2023.S2704-Data.csv') #health insurance breakdown
#excel3.iloc[:,10] #number of old people who could be on medicare USE THIS FOR TOTAL OLD POPULATION
#excel3.iloc[:,18] #numver of old people who could be on medicaid. Medicare is government health insurance for old people, medicaid is
#state level health insurance that goes with and beyond medicare.
#excel3.iloc[:,26] #old people who could be covered by health care
#excel3.iloc[:,68] #old people covered by medicare
#excel3.iloc[:,76] #number of old people covered by medicaid
#excel3.iloc[:,84] #number of old people actually on normal health insurance
#excel3.iloc[:,126] #percent of old people covered by medicare
#excel3.iloc[:,134] #percent of old people covered by medicaid
#excel3.iloc[:,142] #percent of old people on normal health insurance

In [16]:
excel4=pd.read_csv('ACSDT5Y2023.B18135-Data.csv') #disability stuff
#excel4.iloc[:,50] #number of old people with a disability
#excel4.iloc[:,52] #number of old people with a disability and health insurance
#excel4.iloc[:,54] #number of old people with a disability and PRIVATE health insurance
#excel4.iloc[:,56] #number of old people with a disability and public health insurance (aka medicare/medicaid)
#excel4.iloc[:,58] #number of old people with a disability and NO health insurance
#60=not-diabled pop
#62=no disabled yes insurance
#64=able private insurance
#66=public insurance ala medicare/medicade
#68=able, no insurance
###
#Excel 2, 3, 4, 7 have the same rows
###

In [87]:
excel5=pd.read_csv('DECENNIALSF32000.PCT029-Data.csv')
#21-26 is elderly men with mental handicaps (split between 65-74 and 75+)
#45-50 is the same but for elderly women (again split between 65-74 and 75+)
#excel5.iloc[:,26][0]

'Total!!Male!!75 years and over!!No mental disability'

In [10]:
excel6=pd.read_csv('DECENNIALSF32000.P122-Data.csv') #worthless, no actual data

In [35]:
excel7=pd.read_csv('ACSDT5Y2023.B25093-Data.csv')
#excel7.iloc[:,46] #total number of houses/apartments owned by elderly people.

0      Estimate!!Total:!!Householder 65 years and over:
1                                                 21899
2                                                   387
3                                                   321
4                                                   197
                             ...
102                                                 520
103                                                   0
104                                                   4
105                                                   0
106                                                   0
Name: B25093_023E, Length: 107, dtype: object

In [54]:
excel8=pd.read_csv('ACSDT5Y2023.B19037-Data.csv')
#excel8.iloc[:,106] #total number of houses owned by old people
#excel8.iloc[:,138] #108, 110, 112,... 136, 138 make histogram of houses owned by old people

In [69]:
excel9=pd.read_csv('ACSDT5Y2023.B11007-Data.csv')
#excel9.iloc[:,4] #number of houses with old people
#excel9.iloc[:,6] #old people living alone
#excel9.iloc[:,8] #old people NOT living alone
#excel9.iloc[:,10] #old people in a family household
#excel9.iloc[:,12] #old people NOT in a family household and NOT living alone

In [116]:
export1=excel.iloc[:,[0,134,138,544]]
export1.columns=['GEO_ID','social security payouts','retirement income','percent below poverty line']
export2=excel2.iloc[:,[0,148]]
export2.columns=['GEO_ID','number insured']
export3=excel3.iloc[:,[0,10,68,76,84]]
export3.columns=['GEO_ID','population of old people','number covered by medicare','number covered by medicaid','number covered by private insurance']
export4=excel4.iloc[:,[0,50,52,54,56,58,60,62,64,66,68]]
export4.columns=['GEO_ID','number disabled','number disabled with insurance','number disabled with with private insurance',
                 'number disabled with medicare','number disabled without insurance',
                'number abled','numbered abled with insurance','number abled with private insurance',
                 'number abled with public insurance','number abled without insurance']
export5=excel5.iloc[:,[0,21,22,23,24,25,26,45,46,47,48,49,50]]
export5.columns=['GEO_ID','number male 65-74','number male 65-74 mental handicap','number male 65-74 no mental handicap',
                'number male 75+','number male 75+ mental handicap','number male 75+ no mental handicap',
                'number female 65-74','number female 65-74 mental handicap','number female 65-74 no mental handicap',
                'number female 75+','number female 75+ mental handicap','number female 75+ no mental handicap']
export7=excel7.iloc[:,[0,46]]
export7.columns=['GEO_ID','number who own households']
export8=excel8.iloc[:,[0,106,108,110,112,114,116,118,120,122,124,126,128,130,132,134,136,138]]
export8.columns=['GEO_ID','number of houses owned','number <10k','10k-15k','15k-20k','20k-25k','25k-30k','30k-35k',
                 '35k-40k','40k-45k','45k-50k','50k-60k','60k-75k','75-100k','100k-125k','125k-150k','150k-200k','200k+']
export9=excel9.iloc[:,[0,4,6,8,10,12]]
export9.columns=['GEO_ID','Number of households that have an old person','number living alone','number living not alone',
                'number living with family','number living NOT with family']

#merging all the things into 1 dataframe
export=pd.merge(export1, export2, on='GEO_ID',how='inner')
export=pd.merge(export, export3, on='GEO_ID',how='inner')
export=pd.merge(export, export4, on='GEO_ID',how='inner')
#export=pd.merge(export, export5, on='GEO_ID',how='inner') 
#export/excel 5 has different GEO_IDs than the other things for some reason so I am excluding it for time's sake
export=pd.merge(export, export7, on='GEO_ID',how='inner')
export=pd.merge(export, export8, on='GEO_ID',how='inner')
export=pd.merge(export, export9, on='GEO_ID',how='inner')

In [117]:
def deUSifier(ex):
    holder=ex.find('US')
    if holder >= 0:
        return ex[holder+2:]
    else:
        return ex

In [118]:
rename=export['GEO_ID'] #take off everything US and before. AKA only 260650000100, not the 14000000US....
for i in range(len(rename)):
    rename[i]=deUSifier(rename[i])
    
export

,GEO_ID,social security payouts,retirement income,percent below poverty line,number insured,population of old people,number covered by medicare,number covered by medicaid,number covered by private insurance,number disabled,...,75-100k,100k-125k,125k-150k,150k-200k,200k+,Number of households that have an old person,number living alone,number living not alone,number living with family,number living NOT with family
0,Geography,Estimate!!INCOME AND BENEFITS (IN 2023 INFLATI...,Estimate!!INCOME AND BENEFITS (IN 2023 INFLATI...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Estimate!!Insured!!Civilian noninstitutionaliz...,Estimate!!Total!!COVERAGE ALONE OR IN COMBINAT...,Estimate!!Public Coverage!!COVERAGE ALONE OR I...,Estimate!!Public Coverage!!COVERAGE ALONE OR I...,Estimate!!Public Coverage!!COVERAGE ALONE OR I...,Estimate!!Total:!!65 years and over:!!With a d...,...,Estimate!!Total:!!Householder 65 years and ove...,Estimate!!Total:!!Householder 65 years and ove...,Estimate!!Total:!!Householder 65 years and ove...,Estimate!!Total:!!Householder 65 years and ove...,Estimate!!Total:!!Householder 65 years and ove...,Estimate!!Total:!!Households with one or more ...,Estimate!!Total:!!Households with one or more ...,Estimate!!Total:!!Households with one or more ...,Estimate!!Total:!!Households with one or more ...,Estimate!!Total:!!Households with one or more ...
1,26065000100,24936,21799,8.5,330,330,314,36,5,130,...,5,0,0,0,6,251,101,150,150,0
2,26065000400,23611,28446,13.9,337,337,330,45,11,168,...,24,7,0,8,0,269,166,103,103,0
3,26065000600,17272,22569,7.6,144,144,132,66,7,53,...,52,7,0,13,0,136,80,56,39,17
4,26065000700,18111,17879,16.1,273,273,273,1,0,82,...,21,0,0,0,0,224,143,81,81,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,26065007000,21427,24092,13.3,715,715,702,96,0,210,...,72,13,40,0,0,628,343,285,271,14
81,26065980000,-,-,-,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82,26065980100,N,N,0.0,4,4,4,0,0,0,...,0,0,0,0,0,4,4,0,0,0
83,26065980200,-,-,-,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
84,26065980300,-,-,-,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [119]:
export.to_csv('elderly_data_complete.csv')